default_language_version:
    python: python3.12

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '.svg$'
    -   id: end-of-file-fixer
        exclude: '.svg$'
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-yaml

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [ "-l", "--recursive", "-x", "tests" ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.2
    hooks:
      - id: python-safety-dependencies-check
        args: ["--ignore=40459,42498,42852"]
        files: requirements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
     - id: mypy
       args: [--strict, --ignore-missing-imports]
       additional_dependencies:
         - types-requests
         - pytest-mypy
         - sqlalchemy[mypy]

  # Hook for Ruff (managed via Poetry)
  - repo: local
    hooks:
     - id: ruff
       name: ruff
       entry: poetry run ruff check --fix
       language: system
       files: \.py$
     - id: ruff-format
       name: ruff-format
       entry: poetry run ruff format
       language: system
       files: \.py$
